package rules

import (
	"backend/algorithms"
	"fmt"
)

// Rule 8 – Your password must include one of this country
// (Anda harus mencari minimal 10 gambar bendera negara. Tampilkan X bendera saja pada 1 sesi permainan)
func rule8(password string, countrycodes []string) bool {
	fmt.Print("Rule 8: ")
	fmt.Println(containsCountry(password, countrycodes))
	return containsCountry(password, countrycodes)
}

// Check if string contains a special character
func containsCountry(password string, countrycodes []string) bool {
	found := false
	for _, code := range countrycodes {
		if algorithms.BMSearch(password, convertCountryCodeToName(code)) {
			found = true
			break
		}
	}

	return found
}

// Function to convert country code to country name
func convertCountryCodeToName(countryCode string) string {
	if country, exists := countryCodes[countryCode]; exists {
		return country
	}
	return ""
}

var countryCodes = map[string]string{
	"AF": "Afghanistan",
	"AL": "Albania",
	"DZ": "Algeria",
	"AD": "Andorra",
	"AO": "Angola",
	"AR": "Argentina",
	"AM": "Armenia",
	"AU": "Australia",
	"AT": "Austria",
	"AZ": "Azerbaijan",
	"BH": "Bahrain",
	"BD": "Bangladesh",
	"BB": "Barbados",
	"BY": "Belarus",
	"BE": "Belgium",
	"BJ": "Benin",
	"BT": "Bhutan",
	"BO": "Bolivia",
	"BA": "Bosnia",
	"BW": "Botswana",
	"BR": "Brazil",
	"BN": "Brunei",
	"BG": "Bulgaria",
	"BF": "Burkina",
	"BI": "Burundi",
	"KH": "Cambodia",
	"CM": "Cameroon",
	"CA": "Canada",
	"CV": "CapeVerde",
	"CF": "CentralAfricanRepublic",
	"TD": "Chad",
	"CL": "Chile",
	"CN": "China",
	"CO": "Colombia",
	"KM": "Comoros",
	"CG": "Congo",
	"HR": "Croatia",
	"CU": "Cuba",
	"CY": "Cyprus",
	"CZ": "Czechia",
	"DK": "Denmark",
	"DJ": "Djibouti",
	"DM": "Dominica",
	"DO": "DominicanRepublic",
	"TL": "EastTimor",
	"EC": "Ecuador",
	"EG": "Egypt",
	"SV": "ElSalvador",
	"GQ": "EquatorialGuinea",
	"ER": "Eritrea",
	"EE": "Estonia",
	"SZ": "Eswatini",
	"ET": "Ethiopia",
	"FJ": "Fiji",
	"FI": "Finland",
	"FR": "France",
	"GA": "Gabon",
	"GM": "Gambia",
	"GE": "Georgia",
	"DE": "Germany",
	"GH": "Ghana",
	"GR": "Greece",
	"GD": "Grenada",
	"GT": "Guatemala",
	"GN": "Guinea",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HT": "Haiti",
	"HN": "Honduras",
	"HU": "Hungary",
	"IS": "Iceland",
	"IN": "India",
	"ID": "Indonesia",
	"IR": "Iran",
	"IQ": "Iraq",
	"IE": "Ireland",
	"IL": "Israel",
	"IT": "Italy",
	"JM": "Jamaica",
	"JP": "Japan",
	"JO": "Jordan",
	"KZ": "Kazakhstan",
	"KE": "Kenya",
	"KI": "Kiribati",
	"KP": "NorthKorea",
	"KR": "SouthKorea",
	"KW": "Kuwait",
	"KG": "Kyrgyzstan",
	"LA": "Laos",
	"LV": "Latvia",
	"LB": "Lebanon",
	"LS": "Lesotho",
	"LR": "Liberia",
	"LY": "Libya",
	"LI": "Liechtenstein",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"MG": "Madagascar",
	"MW": "Malawi",
	"MY": "Malaysia",
	"MV": "Maldives",
	"ML": "Mali",
	"MT": "Malta",
	"MH": "MarshallIslands",
	"MR": "Mauritania",
	"MU": "Mauritius",
	"MX": "Mexico",
	"FM": "Micronesia",
	"MD": "Moldova",
	"MC": "Monaco",
	"MN": "Mongolia",
	"ME": "Montenegro",
	"MA": "Morocco",
	"MZ": "Mozambique",
	"NA": "Namibia",
	"NR": "Nauru",
	"NP": "Nepal",
	"NL": "Netherlands",
	"NZ": "NewZealand",
	"NI": "Nicaragua",
	"NE": "Niger",
	"NG": "Nigeria",
	"MK": "NorthMacedonia",
	"NO": "Norway",
	"OM": "Oman",
	"PK": "Pakistan",
	"PW": "Palau",
	"PA": "Panama",
	"PG": "PapuaNewGuinea",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Philippines",
	"PL": "Poland",
	"PT": "Portugal",
	"QA": "Qatar",
	"RO": "Romania",
	"RU": "Russia",
	"RW": "Rwanda",
	"KN": "SaintKittsandNevis",
	"LC": "SaintLucia",
	"VC": "SaintVincentandtheGrenadines",
	"WS": "Samoa",
	"SM": "SanMarino",
	"ST": "SaoTomeandPrincipe",
	"SA": "SaudiArabia",
	"SN": "Senegal",
	"RS": "Serbia",
	"SC": "Seychelles",
	"SL": "SierraLeone",
	"SG": "Singapore",
	"SK": "Slovakia",
	"SI": "Slovenia",
	"SB": "SolomonIslands",
	"SO": "Somalia",
	"ZA": "SouthAfrica",
	"SS": "SouthSudan",
	"ES": "Spain",
	"LK": "SriLanka",
	"SD": "Sudan",
	"SR": "Suriname",
	"SE": "Sweden",
	"CH": "Switzerland",
	"SY": "Syria",
	"TW": "Taiwan",
	"TJ": "Tajikistan",
	"TZ": "Tanzania",
	"TH": "Thailand",
	"TG": "Togo",
	"TO": "Tonga",
	"TT": "TrinidadandTobago",
	"TN": "Tunisia",
	"TR": "Turkey",
	"TM": "Turkmenistan",
	"TV": "Tuvalu",
	"UG": "Uganda",
	"UA": "Ukraine",
	"AE": "UnitedArabEmirates",
	"GB": "UnitedKingdom",
	"US": "UnitedStates",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VU": "Vanuatu",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"YE": "Yemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
}
